language: java

jdk:
  - oraclejdk8
  
jobs:
  - name: CogniCrypt_runCI      # required
    type: runCI                 # required
    steps:                      # required
      - IN: nightly-trigger
      
  - name: cp-group1718_nightly
    type: runSh             # required
    steps:                  # required
        - IN: nightly-trigger
        - IN: cp-group1718_branch
          showbuildstatus: true
        - TASK:
            #- script: sudo apt-get install maven     # run this once, if mvn is an unknown command
            - script: cd $CPGROUP1718_BRANCH_STATE
            - script: mkdir -p shippable/testresults
            - script: mkdir -p shippable/codecoverage
            - script: git checkout cp-group1718
            - script: cd mvn-parent
            - script: mvn clean verify surefire:test
    on_success:
        - cp ../target/surefire-reports/*.xml ../shippable/testresults/
        - cd ../shippable/testresults
    on_failure:
        - cp ../target/surefire-reports/*.xml ../shippable/testresults/
        - cd ../shippable/testresults
    on_cancel:
        - script: echo "CANCEL"
  
  - name: ti-group1718_nightly
    type: runSh             # required
    steps:                  # required
        - IN: nightly-trigger
        - IN: ti-group1718_branch
          showbuildstatus: true
        - TASK:
            #- script: sudo apt-get install maven   # run this once, if mvn is an unknown command
            - script: cd $TIGROUP1718_BRANCH_STATE
            - script: mkdir -p shippable/testresults
            - script: mkdir -p shippable/codecoverage
            - script: git checkout ti-group1718
            - script: cd mvn-parent
            - script: mvn clean verify surefire:test
    on_success:
        - cp ../target/surefire-reports/*.xml ../shippable/testresults/
        - cd ../shippable/testresults
    on_failure:
        - cp ../target/surefire-reports/*.xml ../shippable/testresults/
        - cd ../shippable/testresults
    on_cancel:
        - script: echo "CANCEL"
  
  - name: ui-group1718_nightly
    type: runSh             # required
    steps:                  # required
        - IN: nightly-trigger
        - IN: ui-group1718_branch
          showbuildstatus: true
        - TASK:
            #- script: sudo apt-get install maven   # run this once, if mvn is an unknown command
            - script: cd $UIGROUP1718_BRANCH_STATE
            - script: mkdir -p shippable/testresults
            - script: mkdir -p shippable/codecoverage
            - script: git checkout ui-group1718
            - script: cd mvn-parent
            - script: mvn clean verify surefire:test
    on_success:
        - cp ../target/surefire-reports/*.xml ../shippable/testresults/
        - cd ../shippable/testresults
    on_failure:
        - cp ../target/surefire-reports/*.xml ../shippable/testresults/
        - cd ../shippable/testresults
    on_cancel:
        - script: echo "CANCEL"